### ISSUE TITLE
ClosedReceiveChannelException

### ISSUE THREAD

**Issue by CheeseTastisch** [Kotlin/kotlinx-rpc#143]
I'm trying to setup some simple rpc code with the following:

# Shared
```kotlin
@Serializable
data class News(
    val id: Int,
    val title: String,
)

@Serializable
data class Result<Data, Error>(
    val success: Boolean,
    val data: Data?,
    val error: Error?
) {

    companion object {
        fun <Data, Error> success(data: Data): Result<Data, Error> {
            return Result(true, data, null)
        }

        fun <Data, Error> error(error: Error): Result<Data, Error> {
            return Result(false, null, error)
        }
    }

}

interface NewsService : RPC {

    suspend fun getAllNews(): Result<List<News>, String>

    suspend fun getNews(id: Int): Result<News, String>

}
```

# Server
```kotlin
class NewsService(override val coroutineContext: CoroutineContext) : INewsService {

    val news = listOf(
        News(1, "News 1"),
        News(2, "News 2"),
        News(3, "News 3"),
        News(4, "News 4"),
        News(5, "News 5"),
    )

    override suspend fun getAllNews(): Result<List<News>, String> = when (Random.nextInt(0, 100)) {
        in 0..75 -> Result.success(news)
        else -> Result.error("Failed to get news")
    }

    override suspend fun getNews(id: Int): Result<News, String> =
        news.find { it.id == id }
            ?.let { Result.success(it) }
            ?: Result.error("News not found")

}

fun main() {
    embeddedServer(Netty, 8080) {
        install(RPC)
        routing {
            rpc("/rpc") {
                rpcConfig {
                    serialization {
                        json()
                    }
                }

                registerService<INewsService> { ctx -> NewsService(ctx) }
            }
        }
    }.start(wait = true)
}
```

# Client
fun main() = runBlocking {
    val rpcClient = HttpClient { installRPC() }.rpc {
        url("ws://localhost:8080/rpc")
        rpcConfig {
            serialization {
                json()
            }
        }
    }

    streamScoped {
        println(rpcClient.withService<NewsService>().getNews(1))
    }
}

# Result
The client runs normaly and prints out the expected result (`Result(success=true, data=News(id=1, title=News 1), error=null)
`). However, the server throws and exception always at the end, when the client disconnects:
```txt
Exception in thread "eventLoopGroupProxy-3-8" kotlinx.coroutines.channels.ClosedReceiveChannelException: Channel was closed
	at kotlinx.coroutines.channels.BufferedChannel.getReceiveException(BufferedChannel.kt:1760)
	at kotlinx.coroutines.channels.BufferedChannel.resumeWaiterOnClosedChannel(BufferedChannel.kt:2202)
	at kotlinx.coroutines.channels.BufferedChannel.resumeReceiverOnClosedChannel(BufferedChannel.kt:2191)
	at kotlinx.coroutines.channels.BufferedChannel.cancelSuspendedReceiveRequests(BufferedChannel.kt:2184)
	at kotlinx.coroutines.channels.BufferedChannel.completeClose(BufferedChannel.kt:1961)
	at kotlinx.coroutines.channels.BufferedChannel.isClosed(BufferedChannel.kt:2240)
	at kotlinx.coroutines.channels.BufferedChannel.isClosedForSend0(BufferedChannel.kt:2215)
	at kotlinx.coroutines.channels.BufferedChannel.isClosedForSend(BufferedChannel.kt:2212)
	at kotlinx.coroutines.channels.BufferedChannel.completeCloseOrCancel(BufferedChannel.kt:1933)
	at kotlinx.coroutines.channels.BufferedChannel.closeOrCancelImpl(BufferedChannel.kt:1826)
	at kotlinx.coroutines.channels.BufferedChannel.close(BufferedChannel.kt:1785)
	at kotlinx.coroutines.channels.SendChannel$DefaultImpls.close$default(Channel.kt:95)
	at io.ktor.websocket.DefaultWebSocketSessionImpl$runIncomingProcessor$1.invokeSuspend(DefaultWebSocketSession.kt:222)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at kotlinx.coroutines.DispatchedTaskKt.resume(DispatchedTask.kt:231)
	at kotlinx.coroutines.DispatchedTaskKt.resumeUnconfined(DispatchedTask.kt:187)
	at kotlinx.coroutines.DispatchedTaskKt.dispatch(DispatchedTask.kt:159)
	at kotlinx.coroutines.CancellableContinuationImpl.dispatchResume(CancellableContinuationImpl.kt:466)
	at kotlinx.coroutines.CancellableContinuationImpl.resumeImpl(CancellableContinuationImpl.kt:500)
	at kotlinx.coroutines.CancellableContinuationImpl.resumeImpl$default(CancellableContinuationImpl.kt:489)
	at kotlinx.coroutines.CancellableContinuationImpl.resumeWith(CancellableContinuationImpl.kt:364)
	at kotlinx.coroutines.channels.BufferedChannel$BufferedChannelIterator.tryResumeHasNextOnClosedChannel(BufferedChannel.kt:1737)
	at kotlinx.coroutines.channels.BufferedChannel.resumeWaiterOnClosedChannel(BufferedChannel.kt:2204)
	at kotlinx.coroutines.channels.BufferedChannel.resumeReceiverOnClosedChannel(BufferedChannel.kt:2191)
	at kotlinx.coroutines.channels.BufferedChannel.cancelSuspendedReceiveRequests(BufferedChannel.kt:2184)
	at kotlinx.coroutines.channels.BufferedChannel.completeClose(BufferedChannel.kt:1961)
	at kotlinx.coroutines.channels.BufferedChannel.isClosed(BufferedChannel.kt:2240)
	at kotlinx.coroutines.channels.BufferedChannel.isClosedForSend0(BufferedChannel.kt:2215)
	at kotlinx.coroutines.channels.BufferedChannel.isClosedForSend(BufferedChannel.kt:2212)
	at kotlinx.coroutines.channels.BufferedChannel.completeCloseOrCancel(BufferedChannel.kt:1933)
	at kotlinx.coroutines.channels.BufferedChannel.closeOrCancelImpl(BufferedChannel.kt:1826)
	at kotlinx.coroutines.channels.BufferedChannel.close(BufferedChannel.kt:1785)
	at kotlinx.coroutines.channels.SendChannel$DefaultImpls.close$default(Channel.kt:95)
	at io.ktor.websocket.RawWebSocketJvm$1.invokeSuspend(RawWebSocketJvm.kt:81)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:104)
	at io.netty.util.concurrent.AbstractEventExecutor.runTask(AbstractEventExecutor.java:173)
	at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:166)
	at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:469)
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:569)
	at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:994)
	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
	at io.ktor.server.netty.EventLoopGroupProxy$Companion.create$lambda$1$lambda$0(NettyApplicationEngine.kt:296)
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
	at java.base/java.lang.Thread.run(Thread.java:1583)
	Suppressed: kotlinx.coroutines.internal.DiagnosticCoroutineContextException: [CoroutineName(ws-default), StandaloneCoroutine{Cancelling}@76fbb7e7, io.ktor.server.netty.EventLoopGroupProxy@3075d845]
```

This exeption occours, even when I am not calling any rpc method, but just creat the `HttpClient`.

Is this expected behaviour, and if so, why? And if not, how to fix?

**Comment by Mr3zee** [comment]
Hi! I think it was fixed here https://github.com/Kotlin/kotlinx-rpc/pull/141
